# Ein kurzer  Einblick: Pandas und Scikit-learn


--> vgl. für die Dokumentation von Pandas z.B. https://pandas.pydata.org/pandas-docs/stable/

--> vgl. für die Dokumentation von scikit-learn z.B. : https://scikit-learn.org/stable/index.html

--> vgl. zum Iris flower Datensatz z.B. https://en.wikipedia.org/wiki/Iris_flower_data_set

- zum Iris flower Datensatz gibt es sehr viel Dokumentation
- eignet sich daher gut zum "Herumspielen", Kennenlernen, Testen von Methoden

In [1]:
import pandas as pd
import numpy as np

In [2]:
#mit read_csv eine CSV-Datei einlesen

data = pd.read_csv("iris.csv") 

# (mit to_csv in eine CSV-Datei schreiben)

In [3]:
# info zeigt uns ein paar Informationen über den Datensatz

data.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
Id               150 non-null int64
SepalLengthCm    150 non-null float64
SepalWidthCm     150 non-null float64
PetalLengthCm    150 non-null float64
PetalWidthCm     150 non-null float64
Species          150 non-null object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.1+ KB


In [4]:
# DataFrame = zweidimensionales Array (Zeilen und Spalten)
# Series = eindimensionales Array (eine Spalte) 

In [5]:
# Zeilen?

data.axes[0]

RangeIndex(start=0, stop=150, step=1)

In [6]:
# Spalten? 

#data.axes[1]

# oder auch: 
#data.keys()
# data.columns

In [7]:
print("Anzahl der Zeilen: " + str(len(data.axes[0])))
print("Anzahl der Spalten: " + str(len(data.axes[1])))

Anzahl der Zeilen: 150
Anzahl der Spalten: 6


In [8]:
# shape zeigt uns die Dimension des Datensatzes (Zeilen,Spalten)

data.shape 

# für die Zeilen:
#data.shape[0] 

# für die Spalten: 
#data.shape[1]

(150, 6)

In [9]:
# Gibt es fehlende Werte in unserem Datensatz?

#data.isnull()
data.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [10]:
# Die Daten einer bestimmten Spalte anzeigen lassen:

data['SepalLengthCm']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
5      5.4
6      4.6
7      5.0
8      4.4
9      4.9
10     5.4
11     4.8
12     4.8
13     4.3
14     5.8
15     5.7
16     5.4
17     5.1
18     5.7
19     5.1
20     5.4
21     5.1
22     4.6
23     5.1
24     4.8
25     5.0
26     5.0
27     5.2
28     5.2
29     4.7
      ... 
120    6.9
121    5.6
122    7.7
123    6.3
124    6.7
125    7.2
126    6.2
127    6.1
128    6.4
129    7.2
130    7.4
131    7.9
132    6.4
133    6.3
134    6.1
135    7.7
136    6.3
137    6.4
138    6.0
139    6.9
140    6.7
141    6.9
142    5.8
143    6.8
144    6.7
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLengthCm, Length: 150, dtype: float64

In [11]:
# head: die ersten 5 Zeilen anzeigen

data.head() 

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [12]:
# tail: die letzten 5 Zeilen anzeigen

data.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [13]:
# Die ersten drei Zeilen anzeigen lassen:

data[0:3] 

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa

In [14]:
# nur die Blumen enzeigen lassen mit SepalLengthCm > 7

data[data['SepalLengthCm'] > 7]

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
102  103            7.1           3.0            5.9           2.1   
105  106            7.6           3.0            6.6           2.1   
107  108            7.3           2.9            6.3           1.8   
109  110            7.2           3.6            6.1           2.5   
117  118            7.7           3.8            6.7           2.2   
118  119            7.7           2.6            6.9           2.3   
122  123            7.7           2.8            6.7           2.0   
125  126            7.2           3.2            6.0           1.8   
129  130            7.2           3.0            5.8           1.6   
130  131            7.4           2.8            6.1           1.9   
131  132            7.9           3.8            6.4           2.0   
135  136            7.7           3.0            6.1           2.3   

            Species  
102  Iris-virginica  
105  Iris-virginica  
107  Iris-virginica  
109  Iris-virginica  
117  Iris-virginica  
118  Iris-virginica  
122  Iris-virginica  
125  Iris-virginica  
129  Iris-virginica  
130  Iris-virginica  
131  Iris-virginica  
135  Iris-virginica

In [15]:
# nur die Blumen enzeigen lassen mit PetalLengthCm zwischen 5.5 und 6

data[data['PetalLengthCm'].between(5.5, 6)]

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
100  101            6.3           3.3            6.0           2.5   
102  103            7.1           3.0            5.9           2.1   
103  104            6.3           2.9            5.6           1.8   
104  105            6.5           3.0            5.8           2.2   
108  109            6.7           2.5            5.8           1.8   
112  113            6.8           3.0            5.5           2.1   
116  117            6.5           3.0            5.5           1.8   
120  121            6.9           3.2            5.7           2.3   
124  125            6.7           3.3            5.7           2.1   
125  126            7.2           3.2            6.0           1.8   
128  129            6.4           2.8            5.6           2.1   
129  130            7.2           3.0            5.8           1.6   
132  133            6.4           2.8            5.6           2.2   
134  135            6.1           2.6            5.6           1.4   
136  137            6.3           3.4            5.6           2.4   
137  138            6.4           3.1            5.5           1.8   
140  141            6.7           3.1            5.6           2.4   
143  144            6.8           3.2            5.9           2.3   
144  145            6.7           3.3            5.7           2.5   

            Species  
100  Iris-virginica  
102  Iris-virginica  
103  Iris-virginica  
104  Iris-virginica  
108  Iris-virginica  
112  Iris-virginica  
116  Iris-virginica  
120  Iris-virginica  
124  Iris-virginica  
125  Iris-virginica  
128  Iris-virginica  
129  Iris-virginica  
132  Iris-virginica  
134  Iris-virginica  
136  Iris-virginica  
137  Iris-virginica  
140  Iris-virginica  
143  Iris-virginica  
144  Iris-virginica

In [16]:
# Der Mittelwert von PetalWidthCm:

data['PetalWidthCm'].mean()

1.1986666666666672

In [17]:
# auch praktisch: describe gibt uns ein paar statistische Werte

data.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [18]:
# iloc 
# um Daten nach Zeilen- oder Spaltenindex auszuwählen 

#data.iloc[0] # erste Zeile
#data.iloc[1] # zweite Zeile
#data.iloc[-1] #  letzte Zeile 
#data.iloc[0:5] # die ersten fünf Zeilen 

#data.iloc[:,0] # erste Spalte
#data.iloc[:,1] # zweite Spalte
#data.iloc[:,-1] # letzte Spalte

data.iloc[:, 0:2] # nur die ersten beiden Spalten, aber alle Zeilen
#data.iloc[[0,3,6,24], [1,3,5]] # 1., 4., 7., 25. Zeile + 2., 4., 6. Spalte
#data.iloc[0:5, 0:3] # die ersten fünf Zeilen,  die ersten drei Spalten

Id  SepalLengthCm
0      1            5.1
1      2            4.9
2      3            4.7
3      4            4.6
4      5            5.0
5      6            5.4
6      7            4.6
7      8            5.0
8      9            4.4
9     10            4.9
10    11            5.4
11    12            4.8
12    13            4.8
13    14            4.3
14    15            5.8
15    16            5.7
16    17            5.4
17    18            5.1
18    19            5.7
19    20            5.1
20    21            5.4
21    22            5.1
22    23            4.6
23    24            5.1
24    25            4.8
25    26            5.0
26    27            5.0
27    28            5.2
28    29            5.2
29    30            4.7
..   ...            ...
120  121            6.9
121  122            5.6
122  123            7.7
123  124            6.3
124  125            6.7
125  126            7.2
126  127            6.2
127  128            6.1
128  129            6.4
129  130            7.2
130  131            7.4
131  132            7.9
132  133            6.4
133  134            6.3
134  135            6.1
135  136            7.7
136  137            6.3
137  138            6.4
138  139            6.0
139  140            6.9
140  141            6.7
141  142            6.9
142  143            5.8
143  144            6.8
144  145            6.7
145  146            6.7
146  147            6.3
147  148            6.5
148  149            6.2
149  150            5.9

[150 rows x 2 columns]

In [19]:
# loc 
# um Daten nach einem Label (oder anhand einer Bedingung) auszuwählen

#data.loc[:,['SepalLengthCm']] #alle Zeilen der gewählten Spalte 
#data.loc[:4,['SepalLengthCm']] # die ersten fünf Zeilen der gewählten Spalte 

spec = data.set_index('Species')
print(spec.loc['Iris-virginica']) # Alle, die zur Spezies Iris-virginica gehören  

                 Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Species                                                                      
Iris-virginica  101            6.3           3.3            6.0           2.5
Iris-virginica  102            5.8           2.7            5.1           1.9
Iris-virginica  103            7.1           3.0            5.9           2.1
Iris-virginica  104            6.3           2.9            5.6           1.8
Iris-virginica  105            6.5           3.0            5.8           2.2
Iris-virginica  106            7.6           3.0            6.6           2.1
Iris-virginica  107            4.9           2.5            4.5           1.7
Iris-virginica  108            7.3           2.9            6.3           1.8
Iris-virginica  109            6.7           2.5            5.8           1.8
Iris-virginica  110            7.2           3.6            6.1           2.5
Iris-virginica  111            6.5           3.2            5.1 

In [20]:
# loc aber auch um Daten hinzuzufügen oder zu verändern: 

data.loc['150'] = [151, 5.1, 3.5, 1.4, 0.2, 'Iris-neu']
print(data)

# aber lieber wieder löschen:
data = data.drop('150')
print(data)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
5      6            5.4           3.9            1.7           0.4   
6      7            4.6           3.4            1.4           0.3   
7      8            5.0           3.4            1.5           0.2   
8      9            4.4           2.9            1.4           0.2   
9     10            4.9           3.1            1.5           0.1   
10    11            5.4           3.7            1.5           0.2   
11    12            4.8           3.4            1.6           0.2   
12    13            4.8           3.0            1.4           0.1   
13    14            

In [21]:
# ... und es gibt noch viele weitere coole Methoden :-) 

In [22]:
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
5      6            5.4           3.9            1.7           0.4   
6      7            4.6           3.4            1.4           0.3   
7      8            5.0           3.4            1.5           0.2   
8      9            4.4           2.9            1.4           0.2   
9     10            4.9           3.1            1.5           0.1   
10    11            5.4           3.7            1.5           0.2   
11    12            4.8           3.4            1.6           0.2   
12    13            4.8           3.0            1.4           0.1   
13    14            4.3           3.0            1.1           0.1   
14    15            5.8           4.0            1.2           0.2   
15    16            5.7           4.4            1.5           0.4   
16    17            5.4           3.9            1.3           0.4   
17    18            5.1           3.5            1.4           0.3   
18    19            5.7           3.8            1.7           0.3   
19    20            5.1           3.8            1.5           0.3   
20    21            5.4           3.4            1.7           0.2   
21    22            5.1           3.7            1.5           0.4   
22    23            4.6           3.6            1.0           0.2   
23    24            5.1           3.3            1.7           0.5   
24    25            4.8           3.4            1.9           0.2   
25    26            5.0           3.0            1.6           0.2   
26    27            5.0           3.4            1.6           0.4   
27    28            5.2           3.5            1.5           0.2   
28    29            5.2           3.4            1.4           0.2   
29    30            4.7           3.2            1.6           0.2   
..   ...            ...           ...            ...           ...   
120  121            6.9           3.2            5.7           2.3   
121  122            5.6           2.8            4.9           2.0   
122  123            7.7           2.8            6.7           2.0   
123  124            6.3           2.7            4.9           1.8   
124  125            6.7           3.3            5.7           2.1   
125  126            7.2           3.2            6.0           1.8   
126  127            6.2           2.8            4.8           1.8   
127  128            6.1           3.0            4.9           1.8   
128  129            6.4           2.8            5.6           2.1   
129  130            7.2           3.0            5.8           1.6   
130  131            7.4           2.8            6.1           1.9   
131  132            7.9           3.8            6.4           2.0   
132  133            6.4           2.8            5.6           2.2   
133  134            6.3           2.8            5.1           1.5   
134  135            6.1           2.6            5.6           1.4   
135  136            7.7           3.0            6.1           2.3   
136  137            6.3           3.4            5.6           2.4   
137  138            6.4           3.1            5.5           1.8   
138  139            6.0           3.0            4.8           1.8   
139  140            6.9           3.1            5.4           2.1   
140  141            6.7           3.1            5.6           2.4   
141  142            6.9           3.1            5.1           2.3   
142  143            5.8           2.7            5.1           1.9   
143  144            6.8           3.2            5.9           2.3   
144  145            6.7           3.3            5.7           2.5   
145  146        

--------------------

# Daten klassifizieren mit Pandas und Scikit-learn

###  --> Den Datensatz in eine zufällige Reihenfolge bringen / shuffeln:

In [23]:
# mit Pandas:
data = data.sample(frac=1)

In [24]:
# oder mit sklearn:
from sklearn.utils import shuffle
data = shuffle(data)

In [25]:
data.shape

(150, 6)

### --> Den Datensatz aufteilen in Merkmale und Label:

In [26]:
data = data.drop('Id', axis=1) # die Id-Spalte entfernen 

features = data.iloc[:, :-1].values # alle Zeilen, aber nicht die letzte Spalte 
labels = data.iloc[:, 4].values #alle Zeilen, aber nur die letzte Spalte

print("Attributes:\n", features)
print("\nLabels:\n", labels)

Attributes:
 [[6.8 2.8 4.8 1.4]
 [5.8 2.7 4.1 1. ]
 [5.  3.4 1.6 0.4]
 [4.4 3.  1.3 0.2]
 [7.6 3.  6.6 2.1]
 [5.  3.4 1.5 0.2]
 [5.5 2.4 3.8 1.1]
 [4.5 2.3 1.3 0.3]
 [5.4 3.4 1.7 0.2]
 [6.3 2.8 5.1 1.5]
 [5.7 2.9 4.2 1.3]
 [6.5 2.8 4.6 1.5]
 [5.  3.  1.6 0.2]
 [6.6 2.9 4.6 1.3]
 [4.3 3.  1.1 0.1]
 [7.3 2.9 6.3 1.8]
 [5.1 3.5 1.4 0.2]
 [5.1 3.8 1.6 0.2]
 [6.3 3.3 4.7 1.6]
 [7.  3.2 4.7 1.4]
 [6.9 3.1 4.9 1.5]
 [6.1 2.8 4.  1.3]
 [5.1 3.4 1.5 0.2]
 [6.5 3.2 5.1 2. ]
 [4.9 3.1 1.5 0.1]
 [5.7 2.8 4.1 1.3]
 [5.  3.6 1.4 0.2]
 [6.1 3.  4.6 1.4]
 [5.9 3.  4.2 1.5]
 [4.9 2.5 4.5 1.7]
 [5.2 3.5 1.5 0.2]
 [5.9 3.2 4.8 1.8]
 [6.3 3.3 6.  2.5]
 [4.9 2.4 3.3 1. ]
 [7.7 2.6 6.9 2.3]
 [6.8 3.2 5.9 2.3]
 [6.9 3.1 5.4 2.1]
 [5.8 2.7 5.1 1.9]
 [5.1 2.5 3.  1.1]
 [7.2 3.6 6.1 2.5]
 [6.2 2.9 4.3 1.3]
 [6.4 2.8 5.6 2.1]
 [5.8 2.7 3.9 1.2]
 [5.6 3.  4.1 1.3]
 [4.8 3.  1.4 0.3]
 [5.  3.5 1.3 0.3]
 [5.4 3.9 1.3 0.4]
 [6.7 3.  5.  1.7]
 [4.6 3.1 1.5 0.2]
 [5.1 3.8 1.5 0.3]
 [5.5 4.2 1.4 0.2]
 [6.3 2.5 5.  1.9]

In [27]:
features.shape

(150, 4)

In [28]:
labels.shape

(150,)

### --> Nun in Trainings- und Testset aufteilen:
(i.d.R. gibt es auch noch ein Validationset)

In [29]:
from sklearn.model_selection import train_test_split

features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size=0.30, random_state=20)

#random_state wird genutzt, damit wir es reproduzieren können 

In [30]:
# 70% Trainingsdaten 
print(features_train)
print(labels_train)

[[5.  3.4 1.6 0.4]
 [5.  3.4 1.5 0.2]
 [5.1 3.8 1.5 0.3]
 [6.  2.9 4.5 1.5]
 [4.8 3.  1.4 0.3]
 [5.6 2.7 4.2 1.3]
 [5.1 3.7 1.5 0.4]
 [5.9 3.2 4.8 1.8]
 [4.6 3.2 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [6.1 2.8 4.7 1.2]
 [5.7 3.8 1.7 0.3]
 [6.4 2.8 5.6 2.1]
 [7.2 3.6 6.1 2.5]
 [6.9 3.2 5.7 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 2.5 5.8 1.8]
 [5.3 3.7 1.5 0.2]
 [5.9 3.  5.1 1.8]
 [6.5 3.  5.2 2. ]
 [6.7 3.3 5.7 2.1]
 [6.5 3.2 5.1 2. ]
 [7.7 3.8 6.7 2.2]
 [5.  3.2 1.2 0.2]
 [6.3 2.8 5.1 1.5]
 [5.1 2.5 3.  1.1]
 [4.4 3.2 1.3 0.2]
 [5.  3.3 1.4 0.2]
 [6.3 3.4 5.6 2.4]
 [7.  3.2 4.7 1.4]
 [4.6 3.1 1.5 0.2]
 [7.2 3.  5.8 1.6]
 [6.9 3.1 5.4 2.1]
 [5.2 3.5 1.5 0.2]
 [5.5 3.5 1.3 0.2]
 [6.2 2.2 4.5 1.5]
 [6.5 3.  5.5 1.8]
 [7.2 3.2 6.  1.8]
 [4.9 3.  1.4 0.2]
 [5.  2.  3.5 1. ]
 [6.1 2.6 5.6 1.4]
 [5.2 2.7 3.9 1.4]
 [6.4 3.2 5.3 2.3]
 [6.4 3.1 5.5 1.8]
 [6.3 2.3 4.4 1.3]
 [5.4 3.4 1.7 0.2]
 [6.4 2.9 4.3 1.3]
 [6.1 3.  4.6 1.4]
 [7.6 3.  6.6 2.1]
 [4.3 3.  1.1 0.1]
 [5.4 3.9 1.7 0.4]
 [5.  3.5 1.6 0.6]
 [7.7 2.8 6.

In [31]:
# 30 % Testdaten
print(features_test)
print(labels_test)

[[6.7 3.  5.  1.7]
 [5.7 4.4 1.5 0.4]
 [6.7 3.  5.2 2.3]
 [5.8 2.6 4.  1.2]
 [5.8 4.  1.2 0.2]
 [4.7 3.2 1.3 0.2]
 [4.4 2.9 1.4 0.2]
 [6.1 2.8 4.  1.3]
 [6.7 3.1 4.7 1.5]
 [5.  3.  1.6 0.2]
 [5.6 2.8 4.9 2. ]
 [6.  2.2 4.  1. ]
 [6.2 3.4 5.4 2.3]
 [6.8 3.2 5.9 2.3]
 [5.9 3.  4.2 1.5]
 [6.  3.4 4.5 1.6]
 [6.6 2.9 4.6 1.3]
 [7.9 3.8 6.4 2. ]
 [4.9 3.1 1.5 0.1]
 [6.6 3.  4.4 1.4]
 [5.5 4.2 1.4 0.2]
 [5.6 2.9 3.6 1.3]
 [6.  3.  4.8 1.8]
 [6.9 3.1 4.9 1.5]
 [6.7 3.1 4.4 1.4]
 [4.6 3.4 1.4 0.3]
 [4.9 3.1 1.5 0.1]
 [7.7 2.6 6.9 2.3]
 [5.5 2.5 4.  1.3]
 [5.2 4.1 1.5 0.1]
 [6.3 2.5 4.9 1.5]
 [5.1 3.5 1.4 0.3]
 [6.8 2.8 4.8 1.4]
 [5.4 3.9 1.3 0.4]
 [6.5 2.8 4.6 1.5]
 [5.8 2.7 5.1 1.9]
 [6.3 2.7 4.9 1.8]
 [5.8 2.7 4.1 1. ]
 [6.3 2.5 5.  1.9]
 [5.1 3.3 1.7 0.5]
 [5.7 2.5 5.  2. ]
 [6.7 3.1 5.6 2.4]
 [5.8 2.7 5.1 1.9]
 [6.  2.7 5.1 1.6]
 [5.2 3.4 1.4 0.2]]
['Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicol

In [32]:
print(len(features_train))
print(len(features_test))

105
45


### -->  Jetzt können wir schon klassifizieren!

### -->  Naive Bayes Classifier 

In [33]:
from sklearn.naive_bayes import GaussianNB

# den Klassfikator erstellen: 
gnb = GaussianNB()

# den Klassfikator mit dem Trainingsset trainieren: 
gnb.fit(features_train, labels_train)

# den Klassifikator auf das Testset anwenden: 
labels_pred = gnb.predict(features_test)
print("Ergebnis für das Testset:")
print(labels_pred)

# Wie gut funktioniert der Klassifikator?
from sklearn.metrics import accuracy_score

print("\n Treffsicherheit/ Accuracy:")
print(accuracy_score(labels_test, labels_pred))
#print(gnb.score(features_test, labels_test))

Ergebnis für das Testset:
['Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa']

 Treffsicherheit/ Accuracy:
0.9111111111111111


In [34]:
from sklearn.metrics import classification_report

print(classification_report(labels_test, labels_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        14
Iris-versicolor       1.00      0.78      0.88        18
 Iris-virginica       0.76      1.00      0.87        13

      micro avg       0.91      0.91      0.91        45
      macro avg       0.92      0.93      0.91        45
   weighted avg       0.93      0.91      0.91        45



### --> Perceptron Klassifikator:

In [35]:
from sklearn.linear_model import Perceptron

# den Klassfikator trainieren: 
# n_iter = Hyperparameter 
ppn = Perceptron(n_iter=30)

# den Klassfikator mit dem Trainingsset trainieren: 
ppn.fit(features_train, labels_train)

# den Klassifikator auf das Testset anwenden: 
labels_pred = ppn.predict(features_test)
print("Ergebnis für das Testset:")
print(labels_pred)

# Wie gut funktioniert der Klassifikator?
print("\n Treffsicherheit/ Accuracy:")
print(accuracy_score(labels_test, labels_pred))
#print(ppn.score(features_test, labels_test)) 

Ergebnis für das Testset:
['Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica'
 'Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-setosa']

 Treffsicherheit/ Accuracy:
0.6222222222222222


/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:152: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)


### --> K Nearest Neighbor (KNN) Klassifikator:

In [36]:
from sklearn.neighbors import KNeighborsClassifier

# den Klassfikator trainieren: 
# n_neighbors = Hyperparameter 
knn = KNeighborsClassifier(n_neighbors=5)

# den Klassfikator mit dem Trainingsset trainieren: 
knn.fit(features_train, labels_train)

# den Klassifikator auf das Testset anwenden: 
labels_pred = knn.predict(features_test)
print("Ergebnis für das Testset:")
print(labels_pred)

# Wie gut funktioniert der Klassifikator?
print("\n Treffsicherheit/ Accuracy:")
print(accuracy_score(labels_test, labels_pred))
#print(knn.score(features_test, labels_test))

Ergebnis für das Testset:
['Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa']

 Treffsicherheit/ Accuracy:
0.9333333333333333


----------------- 

# Texte vektorisieren mit Scikit-learn

In [37]:
texts = [
    "it's really really cold outside",
    "i prefer hot beverages to cold beverages",
    "to find the best beverages you have to think outside the box",
    "christmas boxes are wrapped as presents"
]

### --> Count Vectorizer

- Konvertiert einen Text / einen Textkorpus in eine Matrix von "token counts"

In [38]:
from sklearn.feature_extraction.text import CountVectorizer

In [39]:
vectorizer = CountVectorizer()

# die Vokabeln lernen:
voc  = vectorizer.fit_transform(texts)

In [40]:
print(vectorizer.get_feature_names())

['are', 'as', 'best', 'beverages', 'box', 'boxes', 'christmas', 'cold', 'find', 'have', 'hot', 'it', 'outside', 'prefer', 'presents', 'really', 'the', 'think', 'to', 'wrapped', 'you']


In [41]:
# gelernte Matrix
voc.toarray()

# Jeder Zeile dieser Matrix spiegelt ein Dokument/ einen Text wieder 
# und ist so lang wie das gesamte Vokabular des Korpus 
# für jedes Wort wird gezählt, wie oft es in dem jeweiligen Text/ Dokument vorgekommen ist 

array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 2, 1, 2, 0, 1],
       [1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0]],
      dtype=int64)

In [42]:
#print(voc.shape)

In [43]:
#vectorizer.vocabulary_.keys()

In [44]:
pd.DataFrame(vectorizer.fit_transform(texts).toarray(), columns=sorted(vectorizer.vocabulary_.keys()))

are  as  best  beverages  box  boxes  christmas  cold  find  have  ...  it  \
0    0   0     0          0    0      0          0     1     0     0  ...   1   
1    0   0     0          2    0      0          0     1     0     0  ...   0   
2    0   0     1          1    1      0          0     0     1     1  ...   0   
3    1   1     0          0    0      1          1     0     0     0  ...   0   

   outside  prefer  presents  really  the  think  to  wrapped  you  
0        1       0         0       2    0      0   0        0    0  
1        0       1         0       0    0      0   1        0    0  
2        1       0         0       0    2      1   2        0    1  
3        0       0         1       0    0      0   0        1    0  

[4 rows x 21 columns]

### oder auch mit n-grams: 

In [45]:
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))

# ngram_range:
# (2,2) = nur Bigramme
# (1,2) = Unigramme und Bigramme
# (1,1) = nur Unigramme 

voc2  = vectorizer2.fit_transform(texts)

In [46]:
print(vectorizer2.get_feature_names())

['are wrapped', 'as presents', 'best beverages', 'beverages to', 'beverages you', 'boxes are', 'christmas boxes', 'cold beverages', 'cold outside', 'find the', 'have to', 'hot beverages', 'it really', 'outside the', 'prefer hot', 'really cold', 'really really', 'the best', 'the box', 'think outside', 'to cold', 'to find', 'to think', 'wrapped as', 'you have']


In [47]:
# gelernte Matrix
print(voc2.toarray())

[[0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0]
 [0 0 1 0 1 0 0 0 0 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 1]
 [1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]]


In [48]:
pd.DataFrame(vectorizer2.fit_transform(texts).toarray(), columns=sorted(vectorizer2.vocabulary_.keys()))

are wrapped  as presents  best beverages  beverages to  beverages you  \
0            0            0               0             0              0   
1            0            0               0             1              0   
2            0            0               1             0              1   
3            1            1               0             0              0   

   boxes are  christmas boxes  cold beverages  cold outside  find the  ...  \
0          0                0               0             1         0  ...   
1          0                0               1             0         0  ...   
2          0                0               0             0         1  ...   
3          1                1               0             0         0  ...   

   really cold  really really  the best  the box  think outside  to cold  \
0            1              1         0        0              0        0   
1            0              0         0        0              0        1   
2            0              0         1        1              1        0   
3            0              0         0        0              0        0   

   to find  to think  wrapped as  you have  
0        0         0           0         0  
1        0         0           0         0  
2        1         1           0         1  
3        0         0           1         0  

[4 rows x 25 columns]

### --> Tf-Idf Vectorizer:

- Konvertiert einen Text / einen Textkorpus in eine Matrix von TF-IDF-Werten


In [49]:
texts_tfidf = [
    "the weather today is the worst within the history of mankind",
    "the largest state in the US is Alaska",
    "the the something here the the",
    "this is the the is this"
]

In [50]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()

voc3 = tfidf_vectorizer.fit_transform(texts_tfidf)

In [51]:
print(tfidf_vectorizer.get_feature_names())

['alaska', 'here', 'history', 'in', 'is', 'largest', 'mankind', 'of', 'something', 'state', 'the', 'this', 'today', 'us', 'weather', 'within', 'worst']


In [52]:
#print(voc3.shape)

In [53]:
# gelernte Matrix
voc3.toarray()

array([[0.        , 0.        , 0.3184927 , 0.        , 0.20328977,
        0.        , 0.3184927 , 0.3184927 , 0.        , 0.        ,
        0.49860812, 0.        , 0.3184927 , 0.        , 0.3184927 ,
        0.3184927 , 0.3184927 ],
       [0.39233234, 0.        , 0.        , 0.39233234, 0.25042065,
        0.39233234, 0.        , 0.        , 0.        , 0.39233234,
        0.40947058, 0.        , 0.        , 0.39233234, 0.        ,
        0.        , 0.        ],
       [0.        , 0.39661633, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.39661633, 0.        ,
        0.82788343, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.49248889,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.40264194, 0.77157901, 0.        , 0.        , 0.        ,
        0.        , 0.        ]])

In [54]:
pd.DataFrame(tfidf_vectorizer.fit_transform(texts_tfidf).toarray(), columns=(tfidf_vectorizer.vocabulary_.keys()))

the   weather     today        is     worst    within   history  \
0  0.000000  0.000000  0.318493  0.000000  0.203290  0.000000  0.318493   
1  0.392332  0.000000  0.000000  0.392332  0.250421  0.392332  0.000000   
2  0.000000  0.396616  0.000000  0.000000  0.000000  0.000000  0.000000   
3  0.000000  0.000000  0.000000  0.000000  0.492489  0.000000  0.000000   

         of   mankind   largest     state        in        us    alaska  \
0  0.318493  0.000000  0.000000  0.498608  0.000000  0.318493  0.000000   
1  0.000000  0.000000  0.392332  0.409471  0.000000  0.000000  0.392332   
2  0.000000  0.396616  0.000000  0.827883  0.000000  0.000000  0.000000   
3  0.000000  0.000000  0.000000  0.402642  0.771579  0.000000  0.000000   

   something      here      this  
0   0.318493  0.318493  0.318493  
1   0.000000  0.000000  0.000000  
2   0.000000  0.000000  0.000000  
3   0.000000  0.000000  0.000000