In [9]:
import numpy as np
from collections import Counter

texts = [
    
    "it's really really cold outside",
    "i prefer hot beverages to cold beverages",
    "to find the best beverages you have to think outside the box",
    "christmas boxes are wrapped as presents"
    
]


vocab = []
for each_sentence in texts:
    current_words = each_sentence.split()
    #print('all', current_words)
    unique_words = list(set(current_words))
    #print('unique', unique_words)
    for each_w in unique_words:
        if each_w not in vocab:
            vocab.append(each_w)

#ich
test_vocab = list(set([word for sentence in texts for word in sentence.split()]))

print(test_vocab)
print(len(test_vocab))

["it's", 'outside', 'as', 'best', 'i', 'find', 'have', 'hot', 'you', 'box', 'beverages', 'the', 'to', 'are', 'really', 'christmas', 'boxes', 'wrapped', 'presents', 'prefer', 'think', 'cold']
22


In [2]:
print(vocab)
print(len(vocab))
#ich
#print(unique_words)

['really', "it's", 'cold', 'outside', 'hot', 'to', 'prefer', 'beverages', 'i', 'the', 'box', 'find', 'best', 'you', 'think', 'have', 'boxes', 'presents', 'christmas', 'wrapped', 'as', 'are']
22
['boxes', 'presents', 'christmas', 'wrapped', 'as', 'are']


In [ ]:
# "it's coldish outside"
# [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, -> len up to 22]
# non-existing words are ignored

In [15]:
def binary_encode(sentence):
    # represent input sentence via matrix with zeros
    # here, matrix is 1D, which means that it's a vector
    encoding = np.zeros(len(vocab))
    # get all unique words to check whether they are in vocab or not (for the current sent.)
    words = set(sentence.split())
    # check if word is in our vocab
    for num, each_w in enumerate(vocab):
        if each_w in words:
            encoding[num] = 1
    return encoding


def frequ_encode(sentence):
    encoding = np.zeros(len(vocab))
    words = set(sentence.split())
    newCounter = Counter(sentence.split())
    print(newCounter)
    for num, each_w in enumerate(vocab):
        if each_w in words:
            encoding[num] = newCounter[each_w]
    return encoding

In [16]:
frequ_encode("to find the best beverages you have to think outside the box")

Counter({'to': 2, 'the': 2, 'find': 1, 'best': 1, 'beverages': 1, 'you': 1, 'have': 1, 'think': 1, 'outside': 1, 'box': 1})


array([0., 0., 1., 0., 0., 2., 0., 0., 1., 1., 1., 1., 1., 1., 1., 2., 0.,
       0., 0., 0., 0., 0.])

In [4]:
binary_encode("it's coldish outside")
#
binary_encode("to find the best beverages you have to think outside the box")

array([0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       0., 0., 0., 0., 0.])

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(binary=True)
vectorizer.fit(texts)




CountVectorizer(analyzer='word', binary=True, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [7]:
vectorizer.vocabulary_.keys()

dict_keys(['it', 'really', 'cold', 'outside', 'prefer', 'hot', 'beverages', 'to', 'find', 'the', 'best', 'you', 'have', 'think', 'box', 'christmas', 'boxes', 'are', 'wrapped', 'as', 'presents'])

In [29]:
vectorizer.get_feature_names()

['are',
 'as',
 'best',
 'beverages',
 'box',
 'boxes',
 'christmas',
 'cold',
 'find',
 'have',
 'hot',
 'it',
 'outside',
 'prefer',
 'presents',
 'really',
 'the',
 'think',
 'to',
 'wrapped',
 'you']

In [8]:
print(vectorizer.transform(texts))

(0, 7)	1
  (0, 11)	1
  (0, 12)	1
  (0, 15)	1
  (1, 3)	1
  (1, 7)	1
  (1, 10)	1
  (1, 13)	1
  (1, 18)	1
  (2, 2)	1
  (2, 3)	1
  (2, 4)	1
  (2, 8)	1
  (2, 9)	1
  (2, 12)	1
  (2, 16)	1
  (2, 17)	1
  (2, 18)	1
  (2, 20)	1
  (3, 0)	1
  (3, 1)	1
  (3, 5)	1
  (3, 6)	1
  (3, 14)	1
  (3, 19)	1


In [34]:
import pandas as pd


pd.DataFrame(vectorizer.transform(texts).toarray(), columns=sorted(vectorizer.vocabulary_.keys()))


are  as  best  beverages  box  boxes  christmas  cold  find  have  ...  it  \
0    0   0     0          0    0      0          0     1     0     0  ...   1   
1    0   0     0          1    0      0          0     1     0     0  ...   0   
2    0   0     1          1    1      0          0     0     1     1  ...   0   
3    1   1     0          0    0      1          1     0     0     0  ...   0   

   outside  prefer  presents  really  the  think  to  wrapped  you  
0        1       0         0       1    0      0   0        0    0  
1        0       1         0       0    0      0   1        0    0  
2        1       0         0       0    1      1   1        0    1  
3        0       0         1       0    0      0   0        1    0  

[4 rows x 21 columns]

In [39]:
texts_tfidf = [
    
    "the weather today is the worst within the history of mankind",
    "the largest state in the US is Alaska",
    "the the something here the the",
    "this is the the is this"
    
]

In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()
tfidf_vectorizer.fit(texts_tfidf)

pd.DataFrame(tfidf_vectorizer.transform(texts_tfidf).toarray(), columns=sorted(tfidf_vectorizer.vocabulary_.keys()))

alaska      here   history        in        is   largest   mankind  \
0  0.000000  0.000000  0.318493  0.000000  0.203290  0.000000  0.318493   
1  0.392332  0.000000  0.000000  0.392332  0.250421  0.392332  0.000000   
2  0.000000  0.396616  0.000000  0.000000  0.000000  0.000000  0.000000   
3  0.000000  0.000000  0.000000  0.000000  0.492489  0.000000  0.000000   

         of  something     state       the      this     today        us  \
0  0.318493   0.000000  0.000000  0.498608  0.000000  0.318493  0.000000   
1  0.000000   0.000000  0.392332  0.409471  0.000000  0.000000  0.392332   
2  0.000000   0.396616  0.000000  0.827883  0.000000  0.000000  0.000000   
3  0.000000   0.000000  0.000000  0.402642  0.771579  0.000000  0.000000   

    weather    within     worst  
0  0.318493  0.318493  0.318493  
1  0.000000  0.000000  0.000000  
2  0.000000  0.000000  0.000000  
3  0.000000  0.000000  0.000000

In [13]:
multidimensional_array = np.eye(3)

In [15]:
multidimensional_array.shape # 3 x 3

(3, 3)

In [16]:
np.zeros(22).shape # 1 x 22

(22,)

In [23]:
multidimensional_array[:, :]

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])